export const labels = {
  AppName: "SECURESIGHT",
  AppName_Sub: "Browser Security Intelligence",
  Header: "Security Health Score",
  Header_Sub: "Your browser environment has",
  Header_Sub1: "moderate risk",
  Header_Sub2: "exposure. 3 critical issues require attention.",
  IP_Tracking: "IP Tracking",
  Media: "Media Permissions",
  Autofill: "Autofill Data",
  Daily: "Daily Media Permission Activity",
  Recommendations: "Personalized Recommendations",
  Footer: "© 2024 SecureSight. All rights reserved.",
  Footer_Platform: "SECURESIGHT INTELLIGENCE PLATFORM",
  Footer_Analysis: "BROWSER SECURITY ANALYSIS",
  Footer_Data: "LIVE DATA",
  Camera_Access_Log: "Camera Access Log",
  Microphone_Access_Log: "Microphone Access Log",
  Blocked_IPs: "Blocked IPs",
  Rouge_Mic_Access: "Rogue Mic Access",
  Camera_Inrusions: "Camera Intrusions",
  Autofill_Exposures: "Autofill Exposures",
  Security_Radar: "Security Radar",
  Media_Usages_Breakdown: "Media Usages Breakdown",
  IP_Request_Volume: "IP Request Volume",
};
